Update unsorted.py
- Fix error C0114: Missing module docstring.
- C0413: Import "import random" should be placed at the top of the module.
- C0411: standard import "import random" should be placed before "import sort_method".