Update sort_method.py & unsorted.py
sort_method.py:
- Add more detail to module docstring.

unsorted.py:
- Add module docstring.
- Fix pylint error C0114: Missing module docstring.