Update sort_method.py & unsorted.py
sort_method.py:
- Fix error C0303: Trailing whitespace.
unsorted.py:
- Fix error C0114: Missing module docstring.
- Fix error C0411: Wrong import order.